let myvar="mayiladuthurai";
const v= "mayilai";

console.log("myvar string is"+myvar)
console.log("myvar string length is"+myvar.length)
console.log(myvar[9])
console.log(myvar.charAt(4))
console.log(myvar.lastIndexOf("a"))
console.log(myvar.slice(5,8))
console.log(myvar.toLowerCase())
console.log(myvar.toUpperCase())
console.log(myvar.includes("s"))
console.log(myvar.split("i"))
console.log(myvar.split(''))

